### ISSUE TITLE
All entities are "unavailable" almost always

### ISSUE THREAD

**Issue by captainnapalm** [marcelm/radonwave#7]
Not sure if there's somewhere I can grab logs for this, but I've found this to be quite unreliable, with most of the entities showing up as unavailable a lot of the time. This is particularly unfortunate as I'm using the temperature value in automations in my office.

**Comment by marcelm** [comment]
Which entities do you mean? (How do you run the script?) The `radonwave.py` script itself just logs its output to a text file and optionally sends the result to an MQTT server.

**Comment by captainnapalm** [comment]
Ugh, sorry, am I in the wrong place? I mean in home assistant.

**Comment by captainnapalm** [comment]
Sorry, I will move this to the sensor.airthings_wave github issues.

**Comment by marcelm** [comment]
No problem! :-)
